"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Copy, Check, Download } from "lucide-react";
import type { ClinicalAnalysis } from "@/lib/types";

interface ExportButtonProps {
  analysis: ClinicalAnalysis;
}

function formatAnalysisAsText(a: ClinicalAnalysis): string {
  let text = "═══════════════════════════════════════\n";
  text += "  MEDBRIEF AI — CLINICAL ANALYSIS REPORT\n";
  text += "═══════════════════════════════════════\n\n";

  // Demographics
  text += `PATIENT: ${a.extractedData.demographics}\n`;
  text += `CHIEF COMPLAINT: ${a.extractedData.chiefComplaint}\n\n`;

  // Clinical Summary
  text += "── CLINICAL IMPRESSION ──\n";
  text += `${a.clinicalSummary}\n\n`;

  // Red Flags
  if (a.redFlags.length > 0) {
    text += "⚠ RED FLAGS\n";
    a.redFlags.forEach((f) => (text += `  • ${f}\n`));
    text += "\n";
  }

  // Differential Diagnosis
  text += "── DIFFERENTIAL DIAGNOSIS ──\n";
  a.differentialDiagnoses
    .sort((x, y) => y.confidence - x.confidence)
    .forEach((dx, i) => {
      text += `  ${i + 1}. ${dx.name} (${dx.confidence}% confidence, ${dx.severity} severity)\n`;
      text += `     ${dx.reasoning}\n`;
      text += `     Key findings: ${dx.keyFindings.join(", ")}\n\n`;
    });

  // Workup
  text += "── WORKUP RECOMMENDATIONS ──\n";
  a.workupRecommendations.forEach((cat) => {
    text += `  [${cat.category}]\n`;
    cat.tests.forEach((t) => {
      text += `    • [${t.priority.toUpperCase()}] ${t.name}: ${t.rationale}\n`;
    });
    text += "\n";
  });

  // Reasoning
  text += "── CLINICAL REASONING ──\n";
  a.reasoningSteps.forEach((step, i) => {
    text += `  ${i + 1}. [${step.type.toUpperCase()}] ${step.title}\n`;
    text += `     ${step.content}\n\n`;
  });

  text += "═══════════════════════════════════════\n";
  text += "Generated by MedBrief AI — For educational purposes only\n";
  text += "═══════════════════════════════════════\n";

  return text;
}

export function ExportButton({ analysis }: ExportButtonProps) {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    const text = formatAnalysisAsText(analysis);
    await navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const text = formatAnalysisAsText(analysis);
    const blob = new Blob([text], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `medbrief-analysis-${new Date().toISOString().slice(0, 10)}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="flex items-center gap-2">
      <Button
        variant="outline"
        size="sm"
        onClick={handleCopy}
        className="gap-1.5"
      >
        {copied ? (
          <>
            <Check className="h-3.5 w-3.5 text-[var(--med-green)]" />
            Copied
          </>
        ) : (
          <>
            <Copy className="h-3.5 w-3.5" />
            Copy Report
          </>
        )}
      </Button>
      <Button
        variant="outline"
        size="sm"
        onClick={handleDownload}
        className="gap-1.5"
      >
        <Download className="h-3.5 w-3.5" />
        Download
      </Button>
    </div>
  );
}
